# Generated by Django 6.1 on 2026-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdgenerator', '0002_githubrun_github_run_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Profile Name')),
                ('variant', models.CharField(default='client', max_length=50, verbose_name='Variant')),
                ('exename', models.CharField(default='rustdesk', max_length=100, verbose_name='EXE Name')),
                ('appname', models.CharField(default='rustdesk', max_length=100, verbose_name='App Name')),
                ('compname', models.CharField(default='Purslane Ltd', max_length=100, verbose_name='Company Name')),
                ('androidappid', models.CharField(default='com.carriez.flutter_hbb', max_length=100, verbose_name='Android App ID')),
                ('serverIP', models.CharField(blank=True, default='', max_length=200)),
                ('key', models.CharField(blank=True, default='', max_length=500)),
                ('apiServer', models.CharField(blank=True, default='', max_length=200)),
                ('urlLink', models.CharField(blank=True, default='', max_length=200)),
                ('downloadLink', models.CharField(blank=True, default='', max_length=200)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='profiles/icons/')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='profiles/logos/')),
                ('privacy_image', models.ImageField(blank=True, null=True, upload_to='profiles/privacy/')),
                ('iconbase64', models.TextField(blank=True, default='')),
                ('logobase64', models.TextField(blank=True, default='')),
                ('privacybase64', models.TextField(blank=True, default='')),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
